// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.OpenBinFolder.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "0F713362-1708-4956-85F7-A3C204735E3C";
        public const string Name = "Open Bin Folder";
        public const string Description = @"Adds an 'Open Bin Folder' to the right click menu of the project for quick access to the builds output folder.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Coding with Calvin";
        public const string Tags = "bin,debug,release,folder,output";
    }
}
